version: '3.8'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: global-web
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=global
      - DB_USER=root
      - DB_PASSWORD=example
    volumes:
      - ./GLOBAL:/var/www/html:rw   # Only app source is mounted

  db:
    image: phpmyadmin/phpmyadmin
    container_name: global-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=global
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql         # Named volume for persistent DB data
      - ./database/init:/docker-entrypoint-initdb.d:ro  # Folder for init scripts

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: global-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=example
    ports:
      - "8081:80"

volumes:
  db_data: